---
- name: system-baseline | fetch sudoers from api
  tags:
    - baseline:sudoers
    - baseline:sudoers:configure
  ansible.builtin.uri:
    url: "{{sigaint_api}}/sudoers"
    method: GET
    return_content: true
  register: request

- name: system-baseline | write sudoers to file
  ansible.builtin.copy:
    content: "{{request.content}}"
    dest: "{{sudoers_path}}"
    mode: '0644'
  tags:
    - baseline:sudoers
    - baseline:sudoers:configure
