---
- name: Baseline system configuration
  hosts: localhost
  connection: local
  handlers:
    - import_tasks: playbooks/handlers.yaml

  tasks:
    # ------------------------------------------------------------------
    # Always-run tasks: load variables and assert supported OS
    # ------------------------------------------------------------------
    - name: Load variable files (ignore missing files)
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - config/defaults.yaml
        - /usr/local/etc/baseline/config.yaml
        - config/os/{{ ansible_distribution | lower }}.yaml
        - config/secrets.yaml
      ignore_errors: true
      tags: always

    - name: Assert that the operating system is supported
      ansible.builtin.assert:
        that: baseline_os is defined
        success_msg: "{{ baseline_os }} is supported."
        fail_msg: "{{ baseline_os }} is not supported."
      tags: always

    # ------------------------------------------------------------------
    # Conditional configuration tasks
    # ------------------------------------------------------------------
    - name: Apply baseline configuration tasks
      ansible.builtin.include_tasks: "playbooks/{{ item }}.yaml"
      loop:
        - cacert
        - repos
        - dns
        - motd
        - timezone
        - ntp
        - skel
        - auth
        - sudoers
        - sshd
        - baseline
        - syslog
        - profile
        - auditd
        - netgroups
        - fleet
        - automatic_updates
        - monitoring
        - moonlight
      when: ('configure_' + item) | default(true)