---
- name: unix-baseline | ntp | deploy file templates
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  notify: "restart chronyd"
  tags:
    - baseline:ntp
    - baseline:ntp:configure
  with_items:
    - { template: "ntp/{{baseline_os}}/chrony.conf.j2", dest: /etc/chrony.conf, mode: "0644" }

- name: unix-baseline | ntp | start services
  ansible.builtin.service:
    name: "chronyd"
    state: started
    enabled: true
  tags:
    - baseline:ntp
    - baseline:ntp:configure