sssd_default_shell: /usr/bin/bash
sssd_override_shell: /usr/bin/bash
ansible_pull_bin: /usr/bin/ansible-pull
sudoers_path: /etc/sudoers

baseline_os: "linux"

ca_cert_path: /etc/pki/ca-trust/source/anchors/ca.crt