# On FreeBSD Bash is located here
sssd_default_shell: /usr/local/bin/bash
sssd_override_shell: /usr/local/bin/bash

# On FreeBSD ansible-pull is located here
ansible_pull_bin: /usr/local/bin/ansible-pull
sudoers_path: /usr/local/etc/sudoers

ca_cert_path: /etc/ssl/certs/freeipa-ca.crt

baseline_os: "freebsd"