# No SSSD or bash on OpenBSD
## sssd_default_shell: /usr/local/bin/bash
## sssd_override_shell: /usr/local/bin/bash

# On FreeBSD ansible-pull is located here
ansible_pull_bin: /usr/local/bin/ansible-pull
sudoers_path: /etc/sudoers

ca_cert_path: /etc/ssl/ipa-cert.pem

baseline_os: "openbsd"